name: Test
on: [push]

jobs:
  build:
    runs-on: linux
    steps:
    - uses: actions/checkout@v2
    - name: Install
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install deps
      run: |
        python -m pip install -U pip
        pip install -e .
    - name: Run tests
      run: pytest
